# This is the network config written by 'subiquity'
network:
  ethernets:
    enp0s3:
      addresses: [192.168.1.17/24]
      gateway4: 192.168.1.254
      nameservers:
          addresses: [192.168.1.254, 8.8.8.8, 1.1.1.1]
      dhcp4: false
      dhcp6: false
  version: 2
