---

- name : installation de mediawiki
  become: true
  hosts: mediawiki
  tasks:

    
    - name: directory of signature files
      file:
        path: /etc/conf_machine
        state: directory

    - name: Creating an empty file
      file:
        path: "/etc/conf_machine/MWA_mediawiki.01.00.00"
        state: touch
      become: yes


    - name: "edit apparmor alias"
      lineinfile:
        dest: /home/appli/MWA_mediawiki/LIVR/wikidevops/LocalSettings.php
        regexp: '^\$wgLogos'
        line: "$wgLogos = [ '1x' => '$wgResourceBasePath/resources/assets/GRA-135.png' ];"
  
...