---

- name : installation de mediawiki
  become: true
  hosts: mediawiki
  tasks:

# UPDATE
    - name: update
      apt:
        name: "*"
        state: latest

# UPGRADE
    - name: upgrade
      apt:
        name: "*"
        state: latest

# UNZIP
#    - name: install unzip package
#      package:
#        name: unzip
#        state: present

# PHP et GIT
    - name: install php et git
      package:
        name: "{{ item }}"
        state: present
      loop:
        - php
        - php-mysql
        - php-xml
        - php-mbstring
        - git

# MySQL
    - name: install mysql
      package:
        name: "{{ item }}"
        state: present
      loop:
        - mysql-server
        - python3-mysqldb

    - name: generate new root password
      command: openssl rand -hex 10
      args:
        creates: /root/.my.cnf
      register: mysql_new_root_pass

    - name: remove anonymous users
      mysql_user:
        name: ""
        state: absent
      when: mysql_new_root_pass.changed

    - name: remove test database
      mysql_db:
        name: test
        state: absent
      when: mysql_new_root_pass.changed

    - name: output new root password
      debug:
        msg: "New root password is {{mysql_new_root_pass.stdout}}"
      when: mysql_new_root_pass.changed

#    - name: update root password

    - name: create my.cnf
      template:
        src: templates/mysql/my.cnf.j2
        dest: /root/.my.cnf
      when: mysql_new_root_pass.changed

# APACHE
    - name: install apache2
      package:
        name: apache2
        state: present

    - name: create apache2 config
      template:
        src: templates/apache2/default.j2
        dest: /etc/apache2/sites-available/default
      notify: restart apache2

#    - name: create project folder

# MEDIAWIKI
#    - name: git clone du projet mediawiki
#      ansible.builtin.git:
#        repo: https://github.com/Bubu25/Projet-MEP-MediaWiki.git
#        branch: Lyndsey-develop
#        single_branch: yes
#        dest: /home/lindsey/projet

    - name : directory appli
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - /home/appli
        - /home/appli/MWA_mediawiki
        - /home/appli/MWA_mediawiki/LIVR
        - /home/appli/MWA_mediawiki/LIVR/01.00.00

    - name: git repo
      uri:
        url: "{{ item }}"
        return_content: true
        dest: /home/appli/MWA_mediawiki/LIVR
      loop:
        - https://github.com/Bubu25/Projet-MEP-MediaWiki/raw/Lyndsey-develop/INPUT/PACKAGE/wikidevops.tar.gz
        - https://github.com/Bubu25/Projet-MEP-MediaWiki/raw/Lyndsey-develop/INPUT/PACKAGE/dump_image.tar.gz
        - https://github.com/Bubu25/Projet-MEP-MediaWiki/raw/Lyndsey-develop/INPUT/PACKAGE/LoGo.tar.gz
        - https://github.com/Bubu25/Projet-MEP-MediaWiki/raw/Lyndsey-develop/INPUT/PACKAGE/Donnees.xml

    - name: untar package
      unarchive:
        src: "{{ item }}"
        dest: /home/appli/MWA_mediawiki/LIVR
        remote_src: yes
      loop:
        - /home/appli/MWA_mediawiki/LIVR/wikidevops.tar.gz
        - /home/appli/MWA_mediawiki/LIVR/dump_image.tar.gz
        - /home/appli/MWA_mediawiki/LIVR/LoGo.tar.gz
      #register: wp_checksum

    - name: création BD mediawiki (mysql)
      mysql_db:
        name: my_wiki
        state: present

    - name: création user mediaWiki (mysql)
      mysql_user:
        name: new_mysql_user
        host: localhost
        password: lindsey
        priv: my_wiki.*:ALL

    - name: création du lien symbolique
      file:
        src: /home/appli/MWA_mediawiki/LIVR/wikidevops/
        dest: /var/www/html/wikidevops
        state: link
      notify: restart apache2

    - name: installation via install.php
      command: "{{ item }}"
      loop:
        - "php install.php --dbname my_wiki --dbuser new_mysql_user --dbpass lindsey --dbserver localhost --server 'http://192.168.56.115' --dbtype mysql --wiki mediawiki -–pass azerty123admin --lang en --scriptpath /wikidevops --confpath /home/appli/MWA_mediawiki/LIVR/wikidevops my_wiki admin"
        - "php importDump.php --wiki my_wiki --server 'http://192.168.56.115' --dbuser new_mysql_user --dbpass lindsey --debug /home/appli/MWA_mediawiki/LIVR/Donnees.xml"
        - "php rebuildrecentchanges.php"
        - "php initSiteStats.php"
        - "php importImages.php --wiki my_wiki --server 'http://192.168.56.115' --dbuser new_mysql_user --dbpass lindsey /home/appli/MWA_mediawiki/LIVR/images"
      args:
        chdir: /home/appli/MWA_mediawiki/LIVR/wikidevops/maintenance

    - name: logo
      shell: sed -i 's/wiki\.png/GRA-135\.png/' /home/appli/MWA_mediawiki/LIVR/wikidevops/LocalSettings.php

    - name: create LocalSetting
      template:
        src: templates/mediawiki/LocalSettings.php
        dest: /home/appli/MWA_mediawiki/LIVR/wikidevops/LocalSettings.php
      notify: restart apache2

#    - name: untar mediawiki
#      unarchive:
#        src: /tmp/mediawiki-1.35.2.tar.gz
#        dest: /var/lib/mediawiki
#        remote_src: yes
#        creates: ?!?

# HANDLERS
  handlers:
    - name: restart apache2
      service:
        name: apache2
        state : restarted
