---

- name : installation de mediawiki
  become: true
  hosts: mediawiki
  tasks:


    - name: Creating an empty file
      file:
        path: "/etc/conf_machine/signature"
        state: touch
...