---

- name : installation de mediawiki
  become: true
  hosts: mediawiki
  tasks:

#APT-UPDATE et UPGRADE
# UPDATE
    # - name: update
    #   apt:
    #     name: "*"
    #     state: latest
# UPGRADE
    - name: upgrade
      apt:
        name: "*"
        state: latest

# PHP
    - name: install php
      package:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - php
        - php-mysql
        - php-xml
        - php-mbstring

# MySQL
    - name: install mysql
      package:
        name: "{{ item }}"
        state: present
      loop:
        - mysql-server
        - python3-mysqldb

    - name: generate new root password
      command: openssl rand -hex 10
      args:
        creates: /root/.my.cnf
      register: mysql_new_root_pass

    - name: remove anonymous users
      mysql_user:
        name: ""
        state: absent
      when: mysql_new_root_pass.changed

    - name: remove test database
      mysql_db:
        name: test
        state: absent
      when: mysql_new_root_pass.changed

    - name: output new root password
      debug:
        msg: "New root password is {{ mysql_new_root_pass.stdout }}"
      when: mysql_new_root_pass.changed



    - name: update root password
      mysql_user:
        name: root
        host: "{{ item }}"
        password: "{{ mysql_new_root_pass.stdout }}"
      loop:
        - "{{ ansible_hostname }}"
        - 127.0.0.1
        - ::1
        - localhost
      when: mysql_new_root_pass.changed

    - name: create my.cnf
      template:
        src: templates/mysql/my.cnf.j2
        dest: /root/.my.cnf
      when: mysql_new_root_pass.changed

# APACHE
    - name: install apache
      package:
        name: apache2
        state: present

#Création directory, recup des tar et decompress

    - name : directory appli
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - /home/appli
        - /home/appli/MWA_mediawiki
        - /home/appli/MWA_mediawiki/LIVR
        - /home/appli/MWA_mediawiki/LIVR/01.00.00

    - name: git repo
      get_url:
        url: "{{ item }}"
 #       return_content: true
        dest: /tmp
      loop:
        - https://github.com/Bubu25/Projet-MEP-MediaWiki/raw/Lyndsey-develop/INPUT/PACKAGE/wikidevops.tar.gz
        - https://github.com/Bubu25/Projet-MEP-MediaWiki/raw/Lyndsey-develop/INPUT/PACKAGE/dump_image.tar.gz
        - https://github.com/Bubu25/Projet-MEP-MediaWiki/raw/Lyndsey-develop/INPUT/PACKAGE/LoGo.tar.gz
        - https://github.com/Bubu25/Projet-MEP-MediaWiki/raw/Lyndsey-develop/INPUT/PACKAGE/Relivraison_24052021.tar.gz
      #register: wp_checksum

    - name: untar package
      unarchive:
        src: "{{ item }}"
        dest: /home/appli/MWA_mediawiki/LIVR
        remote_src: yes
      loop:
        - /tmp/wikidevops.tar.gz
        - /tmp/dump_image.tar.gz
        - /tmp/LoGo.tar.gz
        - /tmp/Relivraison_24052021.tar.gz
        #creates: yes

    - name: move Données
      copy:
        src: /home/appli/MWA_mediawiki/LIVR/LoGo/GRA-135.png
        dest: /home/appli/MWA_mediawiki/LIVR/wikidevops/resources/assets
        remote_src: yes

    - name: chmod
      file:
        dest: /home/appli/MWA_mediawiki/LIVR/wikidevops
        owner: root
        group: www-data
        mode: 0775
        recurse: yes

#Création bdd et user
    - name: Create MySQL DB
      mysql_db:
        name: wikiLN
        state: present

    - name: Create MySQL user
      mysql_user:
        name: userwikiLN
        host: localhost
        password: az
        priv: wikiLN.*:ALL

    - name: création du lien symbolique
      file:
        src: /home/appli/MWA_mediawiki/LIVR/wikidevops
        dest: /var/www/html/wikidevops
        state: link
      notify: restart apache2

    - name: install par script
      command: "{{ item }}"
      loop:
        - "php install.php --dbname wikiLN --dbuser userwikiLN --dbpass az --dbserver localhost --server 'http://192.168.56.106' --dbtype mysql --wiki wikiLN --pass azerty123admin --lang fr --scriptpath /wikidevops --confpath /home/appli/MWA_mediawiki/LIVR/wikidevops wikiLN admin"
        - "php importDump.php --wiki wikiLN --server 'http://192.168.56.106' --dbuser userwikiLN --dbpass az /home/appli/MWA_mediawiki/LIVR/Donnees.xml"
        - "php rebuildrecentchanges.php"
        - "php initSiteStats.php"
        - "php importImages.php --wiki wikiLN --server 'http://192.168.56.106' --dbuser userwikiLN --dbpass az /home/appli/MWA_mediawiki/LIVR/images"
        - "php importImages.php --wiki wikiLN --server 'http://192.168.56.106' --dbuser userwikiLN --dbpass az /home/appli/MWA_mediawiki/LIVR/images/Devops.png"
      args:
        chdir: /home/appli/MWA_mediawiki/LIVR/wikidevops/maintenance

    - name: sed
      shell: sed -i 's/wiki\.png/GRA-135\.png/' /home/appli/MWA_mediawiki/LIVR/wikidevops/LocalSettings.php

      #   - name: create LocalSetting
   #   template:
    #    src: templates/mediawiki/LocalSettings.php
    #    dest: /home/appli/MWA_mediawiki/LIVR/LocalSettings.php
   #   notify: restart apache2

# HANDLERS
  handlers:
    - name: restart apache2
      service:
        name: apache2
        state : restarted
