---

- name : installation de mediawiki
  become: true
  hosts: mediawiki
  tasks:

    
    - name: directory of signature files
      file:
        path: /etc/conf_machine
        state: directory

    - name: Creating an empty file
      file:
        path: "/etc/conf_machine/signature"
        state: touch
...