---

- name : installation de mediawiki
  become: true
  hosts: mediawiki
  tasks:

# UNZIP
    - name: install untar package
      package:
        name: untar
        state: present

# PHP
    - name: install php
      package:
        name: "{{ item }}"
        state: present
      loop:
        - php
        - php-mysql
        - php-xml
        - php-mbstring

# MySQL
    - name: install mysql
      package:
        name: mysql-server
        state: present

    - name: generate new root password
      command: openssl rand -hex 10
      args:
        creates: /root/.my.cnf
      register: mysql_new_root_pass

    - name: remove anonymous users
      mysql_user:
        name: ""
        state: absent
      when: mysql_new_root_pass.changed

    - name: remove test database
      mysql_db:
        name: test
        state: absent
      when: mysql_new_root_pass.changed

    - name: output new root password
      debug:
        msg: "New root password is {{mysql_new_root_pass.stdout}}"
      when: mysql_new_root_pass.changed

    - name: update root password

    - name: create my.cnf
      template:
        src: templates/mysql/my.cnf.j2
        dest: /root/.my.cnf
      when: mysql_new_root_pass.changed

# APACHE
    - name: install apache
      package:
        name: apache2
        state: present

    - name: create apache2 config
      template:
        src: templates/apache2/default.j2
        dest: /etc/apache2/sites-available/default
      notify: restart apache2

    - name: create project folder

# MEDIAWIKI
    - name: download mediawiki
      get_url:
        url: https://releases.wikimedia.org/mediawiki/1.35/mediawiki-1.35.2.tar.gz
        dest: /tmp/mediawiki-1.35.2.tar.gz
        checksum: ?!?

    - name: unzip mediawiki
      unarchive:
        src: /tmp/mediawiki-1.35.2.tar.gz
        dest: /var/lib/mediawiki
        remote_src: ?!?
        creates: ?!?

# HANDLERS
  handlers:
    - name: restart apache2
      service:
        name: apache2
        state : restarted
