---
# tasks file for mw.apache2
# APACHE
- name: install apache
  package:
    name: apache2
    state: present

- name: Copy Apache2 conf
  template:
    src: templates/apache2/apache2.conf.j2
    dest: /etc/apache2/apache2.conf
