---
# tasks file for mw.apache2
# APACHE
- name: install apache
  package:
    name: apache2
    state: present

#- name: www-data
#  ansible.builtin.user:
#    name: www-data
#    uid: 1101

#- name: www-data
#  ansible.builtin.group:
#    name: www-data
#    gid: 1100

- name: Copy Apache2 conf
  template:
    src: templates/apache2/apache2.conf.j2
    dest: /etc/apache2/apache2.conf
  notify: restart apache2
