---
# tasks file for mw.mediawiki
#Création directory, recup des tar et decompress
- name : directory appli
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{dir1}}"
    - "{{dir2}}"
    - "{{dir3}}"
    - "{{dir4}}"

- name: git repo
  get_url:
    url: "{{ item }}"
    dest: "{{dirtar}}"
  loop:
    - "{{repo_file}}/wikidevops.tar.gz"
    - "{{repo_file}}/dump_image.tar.gz"
    - "{{repo_file}}/LoGo.tar.gz"
    - "{{repo_file}}/Relivraison_24052021.tar.gz"

- name: untar package
  unarchive:
    src: "{{ item }}"
    dest: "{{dir4}}"
    remote_src: yes
  loop:
    - "{{dirtar}}/wikidevops.tar.gz"
    - "{{dirtar}}/dump_image.tar.gz"
    - "{{dirtar}}/LoGo.tar.gz"
    - "{{dirtar}}/Relivraison_24052021.tar.gz"


- name: Copy files from foo to bar
  command: "mv {{dir4}}/wikidevops/ {{dir4}}/01.00.00"
  args:
    creates: "{{dir4}}/01.00.00"
    removes: "{{dir4}}/wikidevops/"

- name: Copy files from foo to bar
  command: "mv {{dir4}}/01.00.00/ {{dir3}}/"

- name : directory image
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{dir_wm}}/images/2"
    - "{{dir_wm}}/images/2/21"

- name: move LoGo
  copy:
    src: "{{dir4}}/LoGo/GRA-135.png"
    dest: "{{dir_wm}}/resources/assets"
    remote_src: yes

- name: move image
  copy:
    src: "{{dir4}}/images/DevOps.png"
    dest: "{{dir_wm}}/images/2/21"
    remote_src: yes


- name: move Donnees.xml
  copy:
    src: "{{dir4}}/Donnees.xml"
    dest: "{{dir_wm}}"
    remote_src: yes

- name: chmod
  file:
    dest: "{{dir3}}"
    owner: root
    group: www-data
    mode: 0775
    recurse: yes

- name: Remove old files foo
  file:
    path: "{{dir4}}"
    state: absent

- name: création du lien symbolique
  file:
    src: "{{dir_wm}}"
    dest: /var/www/html/wikidevops
    state: link
  notify: restart apache2

- name: install par script
  command: "{{ item }}"
  loop:
    - "php install.php --dbname {{mysql_bdd}} --dbuser {{mysql_user}} --dbpass {{mysql_pass}} --dbserver localhost --server {{ansible_host}} --dbtype mysql --wiki {{wiki_nom}} --pass {{wiki_pass}} --lang fr --scriptpath /wikidevops --confpath {{dir_wm}} {{wiki_nom}} admin"
    - "php importDump.php --wiki {{wiki_nom}} --server '{{ansible_host}}' --dbuser {{mysql_user}} --dbpass {{mysql_pass}} {{dir_wm}}/Donnees.xml"
    - "php rebuildrecentchanges.php"
    - "php initSiteStats.php"
    - "php importImages.php --wiki {{wiki_nom}} --server '{{ansible_host}}' --dbuser {{mysql_user}} --dbpass {{mysql_pass}} {{dir_wm}}/images"
  args:
    chdir: "{{dir_wm}}/maintenance"

- name: sed
  shell: sed -i 's/wiki\.png/GRA-135\.png/' "{{dir_wm}}/LocalSettings.php"
